spring:
  application:
    name: GuGu_Simple_Upload_Dev
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100GB
      max-request-size: 100GB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://${config.db-server}/${spring.application.name}?serverTimezone=${config.db-timezone}&allowMultiQueries=true
    username: ${config.db-username}
    password: ${config.db-password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 80
logging:
  level:
    com.gugu.upload: debug
config:
  dir: ${user.home}/${spring.application.name}
  # tmp-dir 请确保该文件夹空间足够
  tmp-dir: ${config.dir}/tmp/
  log-dir: ${config.dir}/logs/
  db-server: rm-wz93d1vexp93w779efo.mysql.rds.aliyuncs.com
  db-username: ENC(ICBX0wOJVd/X3jfr1wFvkifHbkil8pAv)
  db-password: ENC(Hm9BC3TwV5eAGtAtYBeGHGdStXVwgwmU)
  db-timezone: Asia/Shanghai