spring:
  application:
    name: GuGu_Simple_Upload
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100GB
      max-request-size: 100GB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://${config.db-server}/${spring.application.name}?serverTimezone=GMT&allowMultiQueries=true
    username: ENC(SOqQqtqr2hBoZOKjBfnyAw==)
    password: ENC(RI8ITLJTJ4ek56gQ7iFzhQ==)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 8841
logging:
  level:
    com.gugu.upload: debug
config:
  dir: ${user.home}/${spring.application.name}
  tmp-dir: ${config.dir}/tmp/
  log-dir: ${config.dir}/log/
  db-server: myserver